name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Access MANAGE_YOUR_RENTERS_BASE_URL
      env:
        MANAGE_YOUR_RENTERS_BASE_URL: ${{secrets.MANAGE_YOUR_RENTERS_BASE_URL}}
      run: echo MANAGE_YOUR_RENTERS_BASE_URL=\"$MANAGE_YOUR_RENTERS_BASE_URL\" > ./local.properties
    - name: Access UNSPLASH_CLIENT_ID
      env: 
        UNSPLASH_CLIENT_ID: ${{secrets.UNSPLASH_CLIENT_ID}}
      run: echo UNSPLASH_CLIENT_ID=\"$UNSPLASH_CLIENT_ID\" > ./local.properties
    - name: Build with Gradle
      run: ./gradlew build
