name: Build
on: [ push, pull_request ]

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Access MANAGE_YOUR_RENTERS_BASE_URL and UNSPLASH_CLIENT_ID
        env:
          UNSPLASH_CLIENT_ID: ${{secrets.UNSPLASH_CLIENT_ID}}
          MANAGE_YOUR_RENTERS_BASE_URL: ${{secrets.MANAGE_YOUR_RENTERS_BASE_URL}}
        run: echo -e "UNSPLASH_CLIENT_ID=\"$UNSPLASH_CLIENT_ID\"\nMANAGE_YOUR_RENTERS_BASE_URL=\"$MANAGE_YOUR_RENTERS_BASE_URL\"" > ./local.properties
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-debug
          path: build/outputs/apk/debug
          branch: master
